import { AgentProfile, AgentRole } from '../agent-types';

export const agentProfiles: Record<AgentRole, AgentProfile> = {
  ceo: {
    role: 'ceo',
    name: 'AI CEO',
    title: 'Giám đốc Chiến lược',
    avatar: 'CEO',
    color: 'bg-gradient-to-br from-amber-500 to-orange-600',
    bgColor: 'bg-amber-50',
    textColor: 'text-amber-700',
    description: 'Thiết lập mục tiêu kinh doanh, giám sát toàn bộ tiến độ công ty',
  },
  hr_director: {
    role: 'hr_director',
    name: 'AI HR Director',
    title: 'Giám đốc Nhân sự',
    avatar: 'HR',
    color: 'bg-gradient-to-br from-purple-500 to-violet-600',
    bgColor: 'bg-purple-50',
    textColor: 'text-purple-700',
    description: 'Phân bổ nhân sự, lập kế hoạch phát triển, đánh giá năng lực',
  },
  finance: {
    role: 'finance',
    name: 'AI CFO',
    title: 'Giám đốc Tài chính',
    avatar: 'CFO',
    color: 'bg-gradient-to-br from-emerald-500 to-green-600',
    bgColor: 'bg-emerald-50',
    textColor: 'text-emerald-700',
    description: 'Quản lý chi phí nhân sự, dự báo ngân sách, tính toán lương thưởng',
  },
  dept_manager: {
    role: 'dept_manager',
    name: 'AI Dept Managers',
    title: 'Trưởng phòng AI',
    avatar: 'TrP',
    color: 'bg-gradient-to-br from-blue-500 to-indigo-600',
    bgColor: 'bg-blue-50',
    textColor: 'text-blue-700',
    description: 'Phân rã mục tiêu phòng ban thành nhiệm vụ cá nhân cho từng nhân viên',
  },
  performance_coach: {
    role: 'performance_coach',
    name: 'AI Coach',
    title: 'Huấn luyện viên Hiệu suất',
    avatar: 'HLV',
    color: 'bg-gradient-to-br from-rose-500 to-pink-600',
    bgColor: 'bg-rose-50',
    textColor: 'text-rose-700',
    description: 'Theo dõi tiến độ, cảnh báo rủi ro, đề xuất cải thiện hiệu suất',
  },
  channel_optimizer: {
    role: 'channel_optimizer',
    name: 'AI Channel Optimizer',
    title: 'Tối ưu Kênh bán hàng',
    avatar: 'CH',
    color: 'bg-gradient-to-br from-cyan-500 to-teal-600',
    bgColor: 'bg-cyan-50',
    textColor: 'text-cyan-700',
    description: 'Phân tích 5 kênh bán (Website, FB/IG, TikTok, Shopee, B2B), ROAS, margin',
  },
  inventory_planner: {
    role: 'inventory_planner',
    name: 'AI Inventory Planner',
    title: 'Kế hoạch Kho & Sản xuất',
    avatar: 'KHO',
    color: 'bg-gradient-to-br from-yellow-500 to-amber-600',
    bgColor: 'bg-yellow-50',
    textColor: 'text-yellow-700',
    description: 'Dự báo nhu cầu, lập kế hoạch sản xuất, cảnh báo tồn kho',
  },
  collection_director: {
    role: 'collection_director',
    name: 'AI Collection Director',
    title: 'Giám đốc Bộ sưu tập',
    avatar: 'BST',
    color: 'bg-gradient-to-br from-fuchsia-500 to-purple-600',
    bgColor: 'bg-fuchsia-50',
    textColor: 'text-fuchsia-700',
    description: 'Quản lý 12 BST/năm, AI design workflow, trend & performance',
  },
  market_research: {
    role: 'market_research',
    name: 'AI Market Research',
    title: 'Nghiên cứu Thị trường',
    avatar: 'MR',
    color: 'bg-gradient-to-br from-sky-500 to-blue-600',
    bgColor: 'bg-sky-50',
    textColor: 'text-sky-700',
    description: 'Phân tích thị trường, đối thủ, trends, cơ hội & rủi ro. Đưa data từ bên ngoài vào.',
  },
  strategy: {
    role: 'strategy',
    name: 'AI Strategy Advisor',
    title: 'Cố vấn Chiến lược',
    avatar: 'STR',
    color: 'bg-gradient-to-br from-red-600 to-rose-700',
    bgColor: 'bg-red-50',
    textColor: 'text-red-700',
    description: 'Chiến lược gia cấp cao. Challenge CEO, tìm blind spots, đề xuất pivots. Không tô hồng.',
  },
};

export const allAgentRoles: AgentRole[] = ['ceo', 'hr_director', 'finance', 'dept_manager', 'performance_coach', 'channel_optimizer', 'inventory_planner', 'collection_director', 'market_research', 'strategy'];

export function getAgentProfile(role: AgentRole): AgentProfile {
  return agentProfiles[role];
}
